language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
  - 4.6

env:
  - NODE_ENV=development

before_install:
  - npm i -g codecov

install:
  - npm install
  
script:
  - npm test
  - codecov

notifications:
  email: false
